# Generated by Django 3.1.6 on 2021-02-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='apk',
            field=models.FileField(blank=True, upload_to='projectsfile'),
        ),
        migrations.AddField(
            model_name='projects',
            name='deb',
            field=models.FileField(blank=True, upload_to='projectsfile'),
        ),
        migrations.AddField(
            model_name='projects',
            name='docs',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projects',
            name='exe',
            field=models.FileField(blank=True, upload_to='projectsfile'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image4',
            field=models.ImageField(blank=True, upload_to='projectspic'),
        ),
        migrations.AddField(
            model_name='projects',
            name='languageAndFrameworks',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='toolsAndSoftware',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='image2',
            field=models.ImageField(upload_to='projectspic'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image3',
            field=models.ImageField(blank=True, upload_to='projectspic'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
