# Generated by Django 3.1.6 on 2021-02-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0004_contacturls_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('subheading', models.CharField(max_length=100)),
                ('about_me', models.TextField(blank=True)),
                ('copyright_text', models.CharField(blank=True, max_length=50)),
                ('copyright_name', models.CharField(blank=True, max_length=30)),
                ('copyright_url', models.URLField(blank=True)),
                ('resume_url', models.URLField(blank=True)),
            ],
        ),
    ]
